x1 = int(input("Dime la coordenada X del primer punto"))
y1 = int(input("Dime la coordenada Y del primer punto"))
x2 = int(input("Dime la coordenada X del segundo punto"))
y2 = int(input("Dime la coordenada Y del segundo punto"))
print("Eje X = " + str((x1 - x2)) + " , Eje Y = " + str((y1 - y2)))